# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-16 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.BooleanField()),
                ('usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='media')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=256)),
                ('apellidos', models.CharField(max_length=256)),
                ('ficha', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('puntaje', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('calificado', 'Calificado'), ('sin calificar', 'Sin Calificar')], max_length=50, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('nombre_grupo', models.CharField(blank=True, default='individual', max_length=50, null=True)),
                ('archivo', models.FileField(upload_to='respuestas')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField()),
                ('hora_publicacion', models.TimeField()),
                ('fecha_limite', models.DateField()),
                ('hora_limite', models.TimeField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=50)),
                ('dificultad', models.CharField(choices=[('basico', 'Basico'), ('medio', 'Medio'), ('dificil', 'Dificil')], max_length=50)),
                ('archivo', models.FileField(upload_to='media')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('incativo', 'Inactivo')], max_length=50)),
                ('like', models.IntegerField(default=0)),
                ('dis_like', models.IntegerField(default=0)),
                ('premio', models.FileField(blank=True, null=True, upload_to='media')),
                ('puntos_maximos', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='persona_reto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Reto'),
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Reto'),
        ),
    ]
